apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysql-operator-role
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "create", "delete", "update"]
  
  - apiGroups: ["otus.homework"] 
    resources: ["mysqls"]      
    verbs: ["get", "list", "create", "delete", "update"]
  
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "delete"]
  
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["create", "delete"]
  
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["create", "delete"]
  
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]

