apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqls.otus.mysql.operator
spec:
  group: otus.mysql.operator
  scope: Namespaced
  names:
    plural: mysqls
    singular: mysql
    kind: MySQLDB
    shortNames:
      - ms
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              required: ["image", "database", "password", "storage_size"]
              properties:
                image:
                  type: string
                  description: "Docker image to use for MySQL instance"
                database:
                  type: string
                  description: "Name of the MySQL database"
                password:
                  type: string
                  description: "Password for MySQL"
                storage_size:
                  type: string
                  description: "Size of the storage for the database"

