apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-nginx
  template:
    metadata:
      labels:
        app: custom-nginx
    spec:
      containers:
      - name: custom-nginx
        image: denysbez/custom-nginx-metrics:latest 
        imagePullPolicy: Always   
        ports:
        - containerPort: 80
        - containerPort: 9113
        env:
        - name: NGINX_PORT
          value: "80"
        - name: METRICS_PORT
          value: "9113"

