apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-nginx
  template:
    metadata:
      labels:
        app: custom-nginx
    spec:
      containers:
        - name: custom-nginx
          image: denysbez/custom-nginx-metrics:latest
          ports:
            - containerPort: 80
          env:
            - name: NGINX_HOST
              value: "localhost"
            - name: NGINX_PORT
              value: "80"

