apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: custom-nginx-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: custom-nginx
  endpoints:
    - port: metrics
      interval: 10s
      path: /metrics
  namespaceSelector:
    matchNames:
      - default

