apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: {{ .Values.volume.pvcName }}
        - name: config-volume
          configMap:
            name: {{ .Values.configMap.name }}
      containers:
        - name: {{ .Release.Name }}-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh
            - -c
            - >
              python3 -m http.server {{ .Values.service.port }} --bind 0.0.0.0 --directory /homework;
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: shared-volume
              mountPath: /homework
            - name: config-volume
              mountPath: /homework/conf
              readOnly: true
          {{- if .Values.probes.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.livenessPath }}
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readinessPath }}
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          {{- end }}
          lifecycle:
            preStop:
              exec:
                command:
                - sh
                - -c
                - >
                  echo "Deleting index.html" &&
                  rm -f /homework/index.html;
      initContainers:
        - name: init-container
          image: busybox
          command:
            - sh
            - -c
            - >
              echo "<html><body>OK</body></html>" > /homework/health.html &&
              echo "<html><body><h1>Welcome to Homework</h1></body></html>" > /homework/index.html 
          volumeMounts:
            - name: shared-volume
              mountPath: /homework
      terminationGracePeriodSeconds: 30

