apiVersion: v1
kind: PersistentVolume
metadata:
  name: homework-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: minikube-hostpath
  hostPath:
    path: /mnt/data/homework-pv

